### ISSUE TITLE
Explicit dependency on `PyQt5`

### ISSUE THREAD

**Issue by jaimergp** [hippover/palmari#1]
Hello team!

The plugin documentation for napari has a set of best practices for developers, which includes a clause recommending _not_ to depend directly on `PyQt5` or `PySide2` to allow end-users to choose their bindings freely. [More details here](https://napari.org/stable/plugins/best_practices.html#don-t-include-pyside2-or-pyqt5-in-your-plugin-s-dependencies).

Is there a reason you need `PyQt5` explicitly or is this more of an oversight? Code search didn't reveal any relevant imports either.

Thanks!

**Comment by hippover** [comment]
No, you’re right, there’s no reason to do so. I’ll remove the dependency in the next release.

Best,

Hippolyte
