### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by goanpeca** [hippover/palmari#2]
Hi @hippover, it seems some dependencies explicitly used (`import foo`) by this package are not listed in the `setup.cfg` file.

See https://github.com/hippover/palmari/blob/main/setup.cfg

The ones I found include:
- click
- pyyaml
- tqdm

Could this be updated?

Also I suggest that the packages listed in https://github.com/hippover/palmari/blob/main/setup.cfg are sorted alphabetically, which makes it much easier to check before a new release, what might be missing.

Cheers! 🚀

**Comment by hippover** [comment]
done !
