### ISSUE TITLE
Package is using PyQt5 imports instead of qtpy

### ISSUE THREAD

**Issue by goanpeca** [hippover/palmari#3]
Hello team!

The plugin documentation for napari has a set of best practices for developers, which includes a clause recommending not to depend directly on PyQt5 or PySide2 to allow end-users to choose their bindings freely. [More details here](https://napari.org/stable/plugins/best_practices.html#don-t-include-pyside2-or-pyqt5-in-your-plugin-s-dependencies).

The files using `PyQt5` instead of `qtpy` are listed here -> https://github.com/hippover/palmari/search?q=pyqt5

Could these imports be updated to use `qtpy` for the next release?

Thanks! 🚀

**Comment by hippover** [comment]
Done !
